config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "posts#index"
  get 'signup' => 'users#new'
  post 'signup' => 'users#create'

  resources :posts
  get 'filter_posts' => 'posts#filter'

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#delete'

  get 'search' => 'youtube#search'
  get 'get_player' => 'youtube#get_player'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/post.rb
class Post < ApplicationRecord
  validates :user_id, presence: true
  validates :video_id, presence: true

  validates :video_id, uniqueness: { scope: :user_id }

  default_scope { order(created_at: :desc) }

  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true

  validates :email, presence: true, uniqueness: { case_sensitive: false },
    format: { with: URI::MailTo::EMAIL_REGEXP }

  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }

  has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper

  rescue_from UnauthorizedError, with: :redirect_to_login

  def redirect_to_login
    respond_to do |format|
      format.html {
        flash[:danger] = 'Login required'
        redirect_to login_path and return
      }
      format.js { head 401 }
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :require_login!, only: [:new, :create]

  PAGE_LIMIT = 10
  DEFAULT_PAGE = 0

  def index
  end

  def filter
    total_count = Post.count
    page = params[:page].to_i || DEFAULT_PAGE

    @posts = Post.includes(:user).all.limit(PAGE_LIMIT).offset(page * PAGE_LIMIT)
    @can_load_more = (page + 1) * PAGE_LIMIT < total_count

    render 'filter', layout: false
  end

  def show
    @post = Post.find(params[:id])

    render 'show', layout: false
  end

  def new
  end

  def create
    service = Posts::Create.new(user: current_user, video_id: params[:video_id])
    service.call

    if service.success?
      flash[:success] = 'Youtube video shared'
      head :ok
    else
      head 500
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :verify_authenticity_token, only: [:delete]

  def new
  end

  def create
    user = User.find_by(email: login_params[:email])

    if user && user.authenticate(login_params[:password])
      login user
      redirect_to posts_path
    else
      flash.now[:danger] = "Invalid email/password"
      render 'new'
    end
  end

  def delete
    logout
    head :ok
  end

  private

  def login_params
    params.require(:session).permit(:email, :password)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      login @user
      redirect_to posts_path
    else
      render 'new'
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/controllers/youtube_controller.rb
class YoutubeController < ApplicationController
  before_action :require_login!, only: [:search]

  def search
    service = Youtube::Search.new(query: params[:query], page_token: params[:page_token])
    service.call

    if service.success?
      @videos_data = service.data[:data]
      @next_page_token = service.data[:next_page_token]

      render 'search', layout: false
    else
      head 500
    end
  end

  def get_player
    service = Youtube::GetDetails.new(video_id: params[:video_id])
    service.call

    if service.success?
      @embed_html = service.data[:embed_html]
      @details = service.data[:details]
      @video_id = params[:video_id]

      render 'get_player', layout: false
    else
      head 500
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  class UnauthorizedError < StandardError; end

  def login(user)
    session[:current_user_id] = user.id
  end

  def current_user
    @current_user ||= User.find_by(id: session[:current_user_id])
  end

  def logged_in?
    !current_user.nil?
  end

  def logout
    session.delete(:current_user_id)
    @current_user = nil
  end

  def require_login!
    unless logged_in?
      raise UnauthorizedError.new
    end
  end
end

app/views/layouts/_header.html.haml
.header
  .title
    %h1
      %a{ href: '/posts' } FunnyMovies
  .content
    - if logged_in?
      .welcome
        = "Welcome #{current_user.name}"
      .button
        = link_to 'Share a movie', new_post_path
      .button.logout
        = 'Log out'
    - else
      .button
        = link_to 'Sign up', signup_path
      .button
        = link_to 'Log in', login_path

:javascript
  $(document).ready( () => {
    $('.button.logout').click( () => {
      $.ajax({
        url: "#{logout_path}",
        method: 'DELETE',
        success: (data, status) => {
          window.location.href = '/'
        }
      })
    })
  })

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title FunnyMovies
    %meta{:content => "width=device-width,initial-scale=1", :name => "viewport"}/
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag "application", "data-turbo-track": "reload"
    = javascript_importmap_tags
    = javascript_include_tag 'https://code.jquery.com/jquery-3.6.4.min.js'
  %body
    - flash.each do |type, message|
      %div{ class: "flash-#{type}" }
        = message
    = render partial: 'layouts/header'
    .content
      = yield

:javascript
  var clearFlash = () => {
    $('.flash-success').remove();
    $('.flash-danger').remove();
  }
  $(document).ready( () => {
    setTimeout(clearFlash, 3000);
  })

app/views/posts/filter.html.haml
- @posts.each do |post|
  .video{ 'data-post-id' => post.id }
    .thumbnail
      = image_tag(post.thumbnail_url)
    .details
      .title
        = post.title.html_safe
      .shared-by
        = "Shared by: #{post.user.name} (#{post.user.email})"
      .description
        %p Description:
        = post.description.html_safe

- if @can_load_more
  .load-more
    Load More

app/views/posts/index.html.haml
.posts-container
  .videos

.modal.post-details
  .modal-content
  .overlay

:javascript
  var callFilterAPI = (currentPage) => {
    $.get(
      "#{filter_posts_path}?page=" + currentPage,
      (data, status) => {
        if (status === 'success') {
          $('.posts-container .videos').append(data);

          $('.load-more').click( (e) => {
            $('.load-more').remove();
            callFilterAPI(currentPage + 1);
          })

          $('.video').click( (e) => {
            e.stopPropagation();
            e.preventDefault();
            var postId = $(e.currentTarget).data('post-id');
            showDetails(postId);
          })
        }
      }
    )
  };

  var showDetails = (postId) => {
    $.get(
      "/posts/" + postId,
      (data, status) => {
        if (status === 'success') {
          $('.modal .modal-content').append(data);
          $('.modal').show();

          $('.modal .close').click( (e) => {
            $('.modal').hide();
            $('.modal .modal-content').empty();
          })
        }
      }
    )
  }

  $(document).ready( () => {
    callFilterAPI(0);

    $('.modal .overlay').on('click', () => {
      $('.modal').hide();
      $('.modal .modal-content').empty();
    });
  })

app/views/posts/new.html.haml
.search-bar
  .input
    = text_field_tag 'search', nil, id: 'search', placeholder: 'Search a video'
  %button#search-button
    Search
.search-result
  .videos

.modal
  .modal-content
  .overlay

:javascript
  var handleSearchSuccess = (data) => {
    $(".search-result .videos").append(data);

    $('.load-more').on('click', () => {
      var query = $('#search').val();
      var nextPageToken = $('.load-more').data('next-page-token');

      callSearchAPI(query, nextPageToken);
    })

    $('.video').click( (e) => {
      e.stopPropagation();
      e.preventDefault();
      var videoId = $(e.currentTarget).data('video-id');
      callGetPlayerAPI(videoId);
    })
  };

  var callSearchAPI = (query, nextPageToken) => {
    $.get(
      "#{search_path}?query=" + query + "&page_token=" + nextPageToken,
      (data, status) => {
        if (status === 'success') {
          $('.load-more').remove();
          handleSearchSuccess(data);
        }
      }
    ).fail( (req, status) => {
      if (req.status === 401) {
        window.location.href = '/login'
      } else {
        alert('Search failed, please try again.');
      }
    } )
  };

  var callGetPlayerAPI = (videoId) => {
    $.get(
      "#{get_player_path}?video_id=" + videoId,
      (data, status) => {
        if (status === 'success') {
          $('.modal .modal-content').append(data);
          $('.modal').show();

          $('.modal #share').click( (e) => {
            var videoId = $(e.currentTarget).data('video-id');
            $.post(
              "/posts",
              { video_id: videoId, authenticity_token: "#{form_authenticity_token}" },
              (data, status) => {
                if (status === 'success') {
                  window.location.href = '/'
                }
              }
            ).fail( () => {
              alert('Create post failed, please try again.')
            })
          })

          $('.modal .close').click( (e) => {
            $('.modal').hide();
            $('.modal .modal-content').empty();
          })
        }
      }
    )
  }

  $(document).ready( () => {
    $('#search').on('keyup', (e) => {
      if (e.key === 'Enter' || e.keyCode === 13) {
        $('.search-result .videos').empty();
        var query = $('#search').val();
        callSearchAPI(query, '');
      }
    });
    $('#search-button').on('click', () => {
      $('.search-result .videos').empty();
      var query = $('#search').val();
      callSearchAPI(query, '');
    })
    $('.modal .overlay').on('click', () => {
      $('.modal').hide();
      $('.modal .modal-content').empty();
    });
  })

app/views/posts/show.html.haml
.video-player
  = @post.embed_html.html_safe
.details
  .close
    = button_tag 'Close'
  .title
    = @post.title
  .shared-by
    = "Shared by: #{@post.user.name} (#{@post.user.email})"
  .description
    %p Description:
    = @post.description.html_safe

app/views/shared/_error_messages.html.haml
.errors
  - if obj.errors.any?
    .summary
      = "The form contains #{ pluralize(obj.errors.count, 'error') }:"
    .details
      %ul
        - obj.errors.full_messages.each do |err_msg|
          %li=err_msg

app/views/users/new.html.haml
%h2 Register

= form_with(model: @user, url: '/signup', data: { turbo: false }) do |f|
  = render partial: 'shared/error_messages', locals: { obj: @user }

  .input-group
    = label_tag :name, 'Name: '
    = f.text_field :name

  .input-group
    = label_tag :email, 'Email: '
    = f.text_field :email

  .input-group
    = label_tag :password, 'Password: '
    = f.password_field :password

  .input-group
    = label_tag :password_confirmation, 'Password Confirmation: '
    = f.password_field :password_confirmation

  = button_tag 'Sign up', type: :submit

app/views/youtube/get_player.html.haml
.video-player
  = @embed_html.html_safe
.details
  .close
    = button_tag 'Close'
  .title
    = @details[:title]
  .description
    = @details[:description]
  #share.action-button{ 'data-video-id' => @video_id }
    = button_tag 'Share'

app/views/youtube/search.html.haml
- @videos_data.each do |video|
  .video{ 'data-video-id' => video[:video_id] }
    .thumbnail
      = image_tag(video[:thumbnail_url])
    .details
      .title
        = video[:title].html_safe
      .description
        = video[:description].html_safe
.load-more{ "data-next-page-token" => "#{@next_page_token}" }
  Load More